### PR TITLE
Update CI to Ubuntu 24.04 runner images

### PR DESCRIPTION
**Pull request by edmorley**
Now that Ubuntu 24.04 images are available on GitHub Actions, we can update from the Ubuntu 22.04 images.

(I'm updating this repo since it's one of the last few that are still using the older runner groups, after which we could clean up those runner groups)

See also:
https://github.com/actions/runner-images/issues/9848
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZRd13d2ce2d455470495cbd34cf

### CODE REVIEW

**Comment by edmorley** [comment]
I had to open this from a fork, since the AAA / All engineering team doesn't have write access to this repo. However, that unfortunately means CI isn't running, since it's only been configured to run on the `push` event, which doesn't apply to forks (and even if it did, PRs from forks wouldn't get secrets set):
https://github.com/heroku/use-app-token-action/blob/127afca8e01ee35e9f60e95a2509462ac58ef5a1/.github/workflows/ci.yaml#L2-L4

**Comment by edmorley** [comment]
Please can I have review?

**Review by Agony1023 — APPROVED** [review]

**Comment by Agony1023** [comment]
@edmorley Just an FYA - We're deprecating this action and recommending folks switch to [actions/create-github-app-token](https://github.com/actions/create-github-app-token).

https://github.com/heroku/use-app-token-action?tab=readme-ov-file#%EF%B8%8F-deprecated-use-github-app-token-action

**Comment by edmorley** [comment]
Yeah I'm aware (I suggested the deprecation in #16) - and all the Languages team repos have already migrated away from it.

I opened this PR because:

> (I'm updating this repo since it's one of the last few that are still using the older runner groups, after which we could clean up those runner groups)

(Even though this Action is deprecated, it's no doubt going to be around for a while longer, and would hold up cleanup of the old runners groups)

**Comment by edmorley** [comment]
@Agony1023 Could you merge? (I don't have permissions to merge this, even now that it's approved)

**Pull request merged**
